# Generated by Django 3.0.5 on 2020-05-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
